name: Continuous Integration Test
on:
    workflow_dispatch:
    push:
    pull_request:
jobs:
    ci_test:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest]
                node: [Release, Debug]
        runs-on: ${{matrix.os}}
        steps:
            - name: Clone Repo
              working-directory: ${{runner.workspace}}
              run: git clone https://github.com/cianciosa/kronmult.git
            - name: Makedir
              working-directory: ${{runner.workspace}}/kronmult
              run: cmake -E make_directory build
            - name: Configure
              working-directory: ${{runner.workspace}}/kronmult/build
              if: matrix.node == 'Debug':
                  - run: cmake -DCMAKE_BUILD_TYPE=${{matrix.node}} -DCMAKE_CXX_FLAGS_DEBUG=-fsanitize=address ../
              if: matrix.node == 'Release':
                  - run: cmake -DCMAKE_BUILD_TYPE=${{matrix.node}} ../
            - name: Build
              working-directory: ${{runner.workspace}}/kronmult/build
              run: make
            - name: Test
              working-directory: ${{runner.workspace}}/kronmult/build
              run: make test
            - name: Show Log
              if: failure()
              working-directory: ${{runner.workspace}}/kronmult/build/Testing/Temporary
              run: cat LastTest.log
